CREATE DATABASE IF NOT EXISTS website_maker;
USE website_maker;

CREATE TABLE IF NOT EXISTS wm_users (
  id INT NOT NULL AUTO_INCREMENT PRIMARY KEY,
  name VARCHAR(60) NOT NULL,
  role ENUM('user', 'admin'),
	create_time TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
	update_time TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
) AUTO_INCREMENT=10000000 DEFAULT CHARSET=utf8;

CREATE TABLE IF NOT EXISTS wm_pages (
  id INT NOT NULL AUTO_INCREMENT PRIMARY KEY,
  title VARCHAR(60) NOT NULL,
	creator_id INT NOT NULL,
	create_time TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
	update_time TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
	config LONGTEXT,
  CONSTRAINT pages_creator_uid FOREIGN KEY(creator_id) REFERENCES wm_users(id)
    ON DELETE RESTRICT
    ON UPDATE CASCADE
) AUTO_INCREMENT=1000000 DEFAULT CHARSET=utf8;

CREATE TABLE IF NOT EXISTS wm_components (
  id INT NOT NULL AUTO_INCREMENT PRIMARY KEY,
  name VARCHAR(60) NOT NULL,
	version VARCHAR(60) NOT NULL,
  creator_id INT NOT NULL,
	display_name VARCHAR(60) NOT NULL,
	css_display VARCHAR(60) NOT NULL,
	create_time TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
	update_time TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  CONSTRAINT components_creator_uid FOREIGN KEY(creator_id) REFERENCES wm_users(id)
    ON DELETE RESTRICT
    ON UPDATE CASCADE
) AUTO_INCREMENT=100000 DEFAULT CHARSET=utf8;

INSERT INTO wm_users (name, role) VALUES ('chd', 'admin');
INSERT INTO wm_pages (title, creator_id) VALUES ('test', 10000000);
UPDATE wm_pages SET title='测试' WHERE id=1000000;
INSERT INTO wm_components (name, version, creator_id, display_name, css_display)
VALUES ('@chd1994/wm-button', '1.0.3', 10000000, '按钮', 'inline-block');
