CREATE DATABASE IF NOT EXISTS website_maker;
USE website_maker;
CREATE TABLE IF NOT EXISTS wm_pages (
  id INT NOT NULL AUTO_INCREMENT PRIMARY KEY,
  name VARCHAR(60) NOT NULL,
	creator VARCHAR(60) NOT NULL,
	create_time TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
	update_time TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP ,
	config LONGTEXT
) AUTO_INCREMENT=100000 DEFAULT CHARSET=utf8;
CREATE TABLE IF NOT EXISTS wm_components (
  id INT NOT NULL AUTO_INCREMENT PRIMARY KEY,
  name VARCHAR(60) NOT NULL,
	version VARCHAR(60) NOT NULL,
	displayName VARCHAR(60) NOT NULL,
	display VARCHAR(60) NOT NULL,
	position VARCHAR(60) NOT NULL,
	create_time TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
	update_time TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
) AUTO_INCREMENT=500000 DEFAULT CHARSET=utf8;

INSERT INTO wm_pages (name, creator) VALUES ('test', 'chd');
UPDATE wm_pages SET name='测试' WHERE id=100000;
INSERT INTO wm_components (name, version, displayName, display, position)
VALUES ('@chd1994/wm-button', '1.0.3', '按钮', 'inline-block', 'static');
